SRC_CPPS = \
           MyEventSink.cpp \
           MyRegisterEventSink.cpp \
           MySource.cpp \
           SoftDeviceGEV.cpp \
           Utilities.cpp \

EXEC     = SoftDeviceGEV

include ../sample.Makefile
